validate templates pre-deploy

diff --git a/azure/bin/create b/azure/bin/create
--- a/azure/bin/create
+++ b/azure/bin/create
@@ -131,6 +131,17 @@ JSON
 ) > .parameters.json
 
 echo "Parameters have been prepared."
+echo "Validating entire setup"
+
+if ! az group deployment validate \
+     --template-file arm/mainTemplate.json \
+     --parameters @.parameters.json \
+     --resource-group "${RESOURCE_GROUP}" >/dev/null ; then
+    echo "Failed validation of templates, cannot continue"
+    exit 1
+fi
+
+
 echo "Deploying templates to S3..."
 
 # Results in HTTP location:
